server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}
    # 위와 같이 데이터베이스 url, username, password 를 작성한 이유
    # 위의 내용들은 OS 의 쉘 언어 환경변수들이다.
    # 이런 환경변수들이 아닌 실제 값을 적어놓는다면 중요한 정보들이 모두 노출되게 된다.
  jpa:
    open-in-view: false
    hibernate:
        ddl-auto: none
    properties:
        '[hibernate.default.batch.fetch.size]': 100


logging:
  level:
    '[shop.mtcoding.bank]': INFO